build:
  python: '3.10'
  modules:
    - ninja
  dependencies:
    - ecmwf/ecbuild@develop
    - ecmwf/eccodes@develop
    - ecmwf/eckit@develop
    - ecmwf/metkit@develop
    - ecmwf/fdb@develop
  dependency_cmake_options:
    - ecmwf/fdb:-DENABLE_LUSTRE=OFF
  parallel: 64
  env:
    - ECCODES_SAMPLES_PATH=$ECCODES_DIR/share/eccodes/samples
    - ECCODES_DEFINITION_PATH=$ECCODES_DIR/share/eccodes/definitions
    - FDB5_CONFIG='{"type":"local","engine":"toc","schema":"'"$TMPDIR"'/pyfdb/tests/default_fdb_schema","spaces":[{"handler":"Default","roots":[{"path":"'"$TMPDIR"'/data/fdb"}]}]}'
    - ECCODES_PYTHON_USE_FINDLIBS=1
  mkdir:
    - data/fdb
