name: cd

on:
  push:
    tags:
      - "**"

jobs:
  deploy-to-pypi:
    name: continuous-delivery-to-pypi
    uses: ecmwf-actions/reusable-workflows/.github/workflows/cd-pypi.yml@v2
    secrets: inherit
